### ISSUE TITLE
Turning OFF Tor entirely doesn't requiring allowing the browser to resolve .onion addresses

### ISSUE THREAD

**Issue by fmarier** [gnukeith/Brave-Hardening-Guide#1]
In this [summary screenshot](https://github.com/gnukeith/Brave-Hardening-Guide?tab=readme-ov-file#summary-1), the option to only resolve `.onion` in Tor windows is checked OFF.

This is not necessary in order to fully disable Tor support in Brave. In fact, what this means is that instead of blocking `.onion` addresses entirely, it will leak them to your DNS resolver (and still fail to resolve them).

The only people who need to toggle this OFF are two who access the Tor network via a custom proxy or through something that their router automatically provides.

**Comment by gnukeith** [comment]
[summary screenshot](https://github.com/gnukeith/Brave-Hardening-Guide?tab=readme-ov-file#summary-1) has been changed to keep "only resolve `.onion` addresses in Tor Windows" ON.

I also added a [important note](https://github.com/gnukeith/Brave-Hardening-Guide?tab=readme-ov-file#important-note-on-brave-tor-settings) about Brave TOR settings with the following details that you provided.

Thank you for creating this issue and letting me know.

Appreciate it.

**Comment by fmarier** [comment]
> I also added a [important note](https://github.com/gnukeith/Brave-Hardening-Guide?tab=readme-ov-file#important-note-on-brave-tor-settings) about Brave TOR settings with the following details that you provided.

That note is spot on. This is a niche setting that's only required in special situations.
